spring:
  datasource:
    url: jdbc:mysql://47.102.192.27:3306/mall?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useOldAliasMetadataBehavior=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    username: root
    password: x12an97g27
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 2
    minIdle: 1
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: false
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,config
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
    useGlobalDataSourceStat: true
  redisson:
      address: 47.102.192.27:6379
      timeout: 3000
      database: 0
      pool:
        max-active: 20
        max-idle: 10
        max-wait: 3000
        min-idle: 4


dubbo:
  application:
    name: pay-services

  protocol:
    name: dubbo
    port: 20883
  registry:
    address: zookeeper://47.102.192.27:2181
    check: true
    group: dubbo-dev
    simplified: true
    ip: 47.102.192.27
  metadata-report:
    address: zookeeper://47.102.192.27:2181
    retry-times: 30
    cycle-report: false
    group: dubbo-dev
  scan:
    base-packages: com.mall.pay.services
logging:
  config:
    classpath: logback.xml
