dubbo:
  application:
    name: mall-user

  registry:
    address: zookeeper://47.102.192.27:2181
    check: true
    group: dubbo-dev
    simplified: true
  metadata-report:
    address: zookeeper://47.102.192.27:2181
    retry-times: 30
    cycle-report: false
    group: dubbo-dev
  scan:
    base-packages: com.mall.user

captchaFlag : false